version: "3"

services:
  publisher:
    build: .
    command: python3 /app/src/publisher_node.py
    environment:
      - ROS_DOMAIN_ID=0
    networks:
      - ros-net

  subscriber:
    build: .
    command: python3 /app/src/subscriber_node.py
    environment:
      - ROS_DOMAIN_ID=0
    networks:
      - ros-net
    depends_on:
      - publisher

networks:
  ros-net:
